version: '2'
services:
  jhipstersampleapplication2-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      - BUCKET=jhipsterSampleApplication2
    # volumes:
    #     - ~/volumes/jhipster/jhipstersampleapplication2/couchbase/:/opt/couchbase/var
