version: '2'
services:
  jhipstersampleapplication2-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      - TYPE=MASTER
      - BUCKET=jhipsterSampleApplication2
  jhipstersampleapplication2-couchbase-node:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    environment:
      - TYPE=WORKER
      - BUCKET=jhipsterSampleApplication2
      - COUCHBASE_MASTER=jhipstersampleapplication2-couchbase
      - AUTO_REBALANCE=false
